# Generated by Django 5.1.3 on 2024-11-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_areas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areas',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Telefone',
            new_name='telefone',
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('carga_horaria', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areas')),
            ],
        ),
    ]
