# Generated by Django 5.1.3 on 2024-11-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_areas_area_rename_cursos_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='descricao',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
