# Generated by Django 5.1.3 on 2024-11-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_area_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='area/'),
        ),
    ]
