# Generated by Django 5.1.3 on 2024-11-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_area_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='endereco',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
