# Generated by Django 5.1.3 on 2024-11-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_curso_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
