# Generated by Django 5.1.3 on 2024-12-06 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
    ]
