name: Django Continuous Integration And Continuous Deploy

on:  
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
  
    steps:
      - uses: actions/checkout@v3
      - name: Install Django
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: install requirements
        run: |
          docker compose build
          docker compose up -d
          docker exec success-guide-django-1 python manage.py test app/tests 
  
  deploy:
    if: github.event_name == 'push'
    needs: continuous-integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Copy files with SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{secrets.TARGET_DIR}}
          EXCLUDE: ".github/**,**.env,.ssh/**"

